apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kafka-listener
  name: kafka-listener
spec:
  containers:
  - image: aicp/aicp-kafka-listener:2.0.0
    name: kafka-listener
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
