apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-log-parser
data:
  fluentd.conf: |
    <match kubernetes.var.log.containers.**fluentd**.log>
      @type null
    </match>
    
    <match kubernetes.**>
      @type stdout
    </match>